spring.application.name=avisosBBDD
spring.datasource.url=jdbc:postgresql://localhost:5432/avisos
spring.datasource.username=eloy
spring.datasource.password=tallereloy
spring.jpa.hibernate.ddl-auto=validate
